SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `accounts`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `blogs`;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `rattings`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `blog_categories`;
DROP TABLE IF EXISTS `blog_comments`;
DROP TABLE IF EXISTS `blog_rattings`;

SET FOREIGN_KEY_CHECKS = 1;
