// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: blogging/comment.proto

package blogging

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CommentService_GetBlogComments_FullMethodName   = "/blogging.CommentService/GetBlogComments"
	CommentService_CreateBlogComment_FullMethodName = "/blogging.CommentService/CreateBlogComment"
)

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentServiceClient interface {
	GetBlogComments(ctx context.Context, in *GetBlogCommentsRequest, opts ...grpc.CallOption) (*GetBlogCommentsResponse, error)
	CreateBlogComment(ctx context.Context, in *CreateBlogCommentsRequest, opts ...grpc.CallOption) (*CreateBlogCommentsResponse, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) GetBlogComments(ctx context.Context, in *GetBlogCommentsRequest, opts ...grpc.CallOption) (*GetBlogCommentsResponse, error) {
	out := new(GetBlogCommentsResponse)
	err := c.cc.Invoke(ctx, CommentService_GetBlogComments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) CreateBlogComment(ctx context.Context, in *CreateBlogCommentsRequest, opts ...grpc.CallOption) (*CreateBlogCommentsResponse, error) {
	out := new(CreateBlogCommentsResponse)
	err := c.cc.Invoke(ctx, CommentService_CreateBlogComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
// All implementations should embed UnimplementedCommentServiceServer
// for forward compatibility
type CommentServiceServer interface {
	GetBlogComments(context.Context, *GetBlogCommentsRequest) (*GetBlogCommentsResponse, error)
	CreateBlogComment(context.Context, *CreateBlogCommentsRequest) (*CreateBlogCommentsResponse, error)
}

// UnimplementedCommentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCommentServiceServer struct {
}

func (UnimplementedCommentServiceServer) GetBlogComments(context.Context, *GetBlogCommentsRequest) (*GetBlogCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlogComments not implemented")
}
func (UnimplementedCommentServiceServer) CreateBlogComment(context.Context, *CreateBlogCommentsRequest) (*CreateBlogCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBlogComment not implemented")
}

// UnsafeCommentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServiceServer will
// result in compilation errors.
type UnsafeCommentServiceServer interface {
	mustEmbedUnimplementedCommentServiceServer()
}

func RegisterCommentServiceServer(s grpc.ServiceRegistrar, srv CommentServiceServer) {
	s.RegisterService(&CommentService_ServiceDesc, srv)
}

func _CommentService_GetBlogComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).GetBlogComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_GetBlogComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).GetBlogComments(ctx, req.(*GetBlogCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_CreateBlogComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).CreateBlogComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_CreateBlogComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).CreateBlogComment(ctx, req.(*CreateBlogCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentService_ServiceDesc is the grpc.ServiceDesc for CommentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blogging.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlogComments",
			Handler:    _CommentService_GetBlogComments_Handler,
		},
		{
			MethodName: "CreateBlogComment",
			Handler:    _CommentService_CreateBlogComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blogging/comment.proto",
}
