openapi: 3.0.1
info:
  title: Kang-Blogging APIs
  description: blogging management
  version: v1.0.0
servers:
  - url: 'https://localhost:10080'
    description: local
paths:
  /api/v1/login:
    post:
      tags:
        - IAM
      summary: '[IAM] Login with username and password'
      description: |-
        - Login with username and password
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: login via username (email, phonen number,...)
                  example: test@123
                password:
                  type: string
                  description: password
                  example: hehehe
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseAPIResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          access_token:
                            type: string
                            description: access token (jwt)
                          refresh_token:
                            type: string
                            description: refresh token (jwt)
                          user_infor:
                            type: array
                            description: List campaigns
                            items:
                              $ref: '#/components/schemas/UserInfo'

        '400':
          description: |-
            400001: `Invalid username or password`: Invalid params
          content:
            application/json:
              examples:
                400_001 - Invalid params:
                  summary: 400_001 - Invalid params
                  description: Invalid params
                  value:
                    code: '400_001'
                    message: Invalid params
        '500':
          description: |-
            500000: `Internal Server Error`: Internal Server Error
          content:
            application/json:
              examples:
                500_000 - Server error:
                  summary: 500_000 - Server error (Server AirDrop Error)
                  description: internal error
                  value:
                    code: '500_000'
                    message: Internal Server Error
  /api/v1/register:
    post:
      tags:
        - IAM
      summary: '[IAM] Register services'
      description: |-
        - Register api
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: login via username (email, phonen number,...)
                  example: test@123
                password:
                  type: string
                  description: password
                  example: hehehe
      responses:
        '200':
          description: Success
        '400':
          description: |-
            400001: `Invalid username or password`: Invalid params
          content:
            application/json:
              examples:
                400_001 - Invalid params:
                  summary: 400_001 - Invalid params
                  description: Invalid params
                  value:
                    code: '400_001'
                    message: Invalid params
        '500':
          description: |-
            500000: `Internal Server Error`: Internal Server Error
          content:
            application/json:
              examples:
                500_000 - Server error:
                  summary: 500_000 - Server error (Server AirDrop Error)
                  description: internal error
                  value:
                    code: '500_000'
                    message: Internal Server Error
  /api/v1/get-user-info:
    get:
      tags:
        - User
      description: |-
        - get user by params.
      summary: 'Get list users'
      operationId: getUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/UserInfo'
components:
  schemas:
    BaseAPIResponse:
      type: object
      properties:
        code:
          type: string
          example: 0
        message:
          type: string
          description: response message
          example: success
    UserInfo:
      type: object
      properties:
        id:
          type: string
          example: uuid
        name:
          type: string
          example: DUT
        avatar:
          type: string
        total_blog:
          type: integer
