openapi: 3.0.1
info:
  title: Kang-Blogging APIs
  description: blogging management
  version: v1.0.0
servers:
  - url: 'https://localhost:10080'
    description: local
paths:
  /api/v1/login:
    post:
      tags:
        - IAM
      summary: '[IAM] Login with username and password'
      description: |-
        - Login with username and password
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: login via username (email, phonen number,...)
                  example: test@123
                password:
                  type: string
                  description: password
                  example: hehehe
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseAPIResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          access_token:
                            type: string
                            description: access token (jwt)
                          refresh_token:
                            type: string
                            description: refresh token (jwt)
                          user_infor:
                            type: array
                            description: List campaigns
                            items:
                              $ref: '#/components/schemas/UserInfo'

        '400':
          description: |-
            400001: `Invalid username or password`: Invalid params
          content:
            application/json:
              examples:
                400_001 - Invalid params:
                  summary: 400_001 - Invalid params
                  description: Invalid params
                  value:
                    code: '400_001'
                    message: Invalid params
        '500':
          description: |-
            500000: `Internal Server Error`: Internal Server Error
          content:
            application/json:
              examples:
                500_000 - Server error:
                  summary: 500_000 - Server error (Server AirDrop Error)
                  description: internal error
                  value:
                    code: '500_000'
                    message: Internal Server Error
  /api/v1/register:
    post:
      tags:
        - IAM
      summary: '[IAM] Register services'
      description: |-
        - Register api
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - display_name
                - email
                - gender
                - birth_day
                - username
                - password
              properties:
                username:
                  type: string
                  description: login via username (email, phonen number,...)
                  example: test@123
                password:
                  type: string
                  description: password
                  example: hehehe
                name:
                  type: string
                  description: full name
                  example: Truong Quang Khang
                display_name:
                  type: string
                  description: Display name
                  example: khang-cute-123
                email:
                  type: string
                  description: Email
                phone_numbers:
                  type: string
                  description: 0123456789
                gender:
                  type: boolean
                  description: Male/Female
                birth_day:
                  type: integer
                  description: Day of birth (unix timestamp)
                avatar:
                  type: string
                  description: Link url of a image
      responses:
        '200':
          description: Success
        '400':
          description: |-
            400001: `Invalid username or password`: Invalid params
          content:
            application/json:
              examples:
                400_001 - Invalid params:
                  summary: 400_001 - Invalid params
                  description: Invalid params
                  value:
                    code: '400_001'
                    message: Invalid params
        '500':
          description: |-
            500000: `Internal Server Error`: Internal Server Error
          content:
            application/json:
              examples:
                500_000 - Server error:
                  summary: 500_000 - Server error (Server AirDrop Error)
                  description: internal error
                  value:
                    code: '500_000'
                    message: Internal Server Error
  /api/v1/get-user-info:
    get:
      tags:
        - User
      description: |-
        - get user by params.
      summary: 'Get list users'
      operationId: getUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseAPIResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          users:
                            type: array
                            description: list users
                            items:
                              $ref: '#/components/schemas/UserInfo'
        '500':
          description: |-
            500000: `Internal Server Error`: Internal Server Error
          content:
            application/json:
              examples:
                500_000 - Server error:
                  summary: 500_000 - Server error (Server AirDrop Error)
                  description: internal error
                  value:
                    code: '500_000'
                    message: Internal Server Error
  /api/v1/get-user-info/{user_id}:
    get:
      tags:
        - User
      description: |-
        - get user by params.
      summary: 'Get list users'
      operationId: getUserDetail
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseAPIResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          user:
                            $ref: '#/components/schemas/UserInfo'
  /api/v1/blog:
    get:
      tags:
        - Blog
      description: |-
        - get list blog
      summary: 'Get blog with params'
      operationId: getBlog
      parameters:
        - in: query
          name: categories
          required: false
          schema:
            type: string
          description: Query blogs with list categoriesIDs (get all with empty this params)
          example: '1,2,3,...'
        - in: query
          name: createdBy
          required: false
          schema:
            type: string
          description: Query blogs with list author ids (get all with empty this params)
          example: '1,2,3,...'
        - in: query
          name: page
          required: true
          schema:
            type: integer
          description: Current page, for high performance try to use pagination.offset instead! (default 1)
        - in: query
          name: pageSize
          required: true
          description: Total item in a page (default is 10)
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseAPIResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          blogs:
                            type: array
                            items:
                              $ref: '#/components/schemas/BlogMetadata'
                          pagination:
                            $ref: '#/components/schemas/Pagination'

components:
  schemas:
    BaseAPIResponse:
      type: object
      properties:
        code:
          type: string
          example: 0
        message:
          type: string
          description: response message
          example: success
    UserInfo:
      type: object
      properties:
        id:
          type: string
          example: uuid
        name:
          type: string
          example: quang khang
        gender:
          type: boolean
          example: true
        display_name:
          type: string
          example: 1kang
        email:
          type: string
          example: knag@123
        avatar:
          type: string
        total_blog:
          type: integer
        total_follower:
          type: integer
          example: 12
        is_active:
          type: boolean
          example: true
        followed_by_me:
          type: boolean
          example: true
          
    UserInfoMetadata:
      type: object
      properties:
        id:
          type: string
          example: uuid
        name:
          type: string
          example: quang khang
        gender:
          type: boolean
          example: true
        display_name:
          type: string
          example: 1kang
        followed_by_me:
          type: boolean
          example: true

    BlogMetadata:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        thumail:
          type: string
        created_at:
          type: integer
        author:
          $ref: '#/components/schemas/UserInfoMetadata'

    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        pageSize:
          type: integer
          example: 10
        total:
          type: integer
          example: 10

