name: Dockerized-SQL

on:
  push:
    branches:
      - master
    paths:
      - 'sql/blogging/**/*'

jobs:
  dockerize:
    name: Dockerized
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dockerized
        run: |
          echo 'Building docker image sql $IMAGE_REPOSITORY:$IMAGE_TAG'
          chmod +x ./scripts/dockerize.sh
          ./scripts/dockerize.sh $IMAGE_TAG $IMAGE_REPOSITORY $TYPE $SERVICE true
        env:
          IMAGE_TAG: m-${{ github.sha }}
          IMAGE_REPOSITORY: truongquangkhang/kang-blogging-sql
          TYPE: sql
          SERVICE: blogging

      - name: Docker push
        run: |
          docker push $IMAGE_REPOSITORY:$IMAGE_TAG
        env:
          IMAGE_TAG: m-${{ github.sha }}
          IMAGE_REPOSITORY: truongquangkhang/kang-blogging-sql

  deploy:
    needs: [dockerize]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.KANGBLOGGING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KANGBLOGGING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KANGBLOGGING_AZURE_SUBSCRIPTION_ID }}

      - name: Update image-tag for container of job
        run: |
          az containerapp job update -n $ACAJ_NAME -g $AZG_NAME \
          --container-name $ACAJ_NAME \
          --image $IMAGE_REPOSITORY:$IMAGE_TAG
        env:
          AZG_NAME: kang
          ACAJ_NAME: kang-blogging-sql
          IMAGE_TAG: m-${{ github.sha }}
          IMAGE_REPOSITORY: truongquangkhang/kang-blogging-sql

      - name: Start job migrations data
        run: |
          az containerapp job start -n $ACAJ_NAME -g $AZG_NAME \
          --container-name $ACAJ_NAME
        env:
          AZG_NAME: kang
          ACAJ_NAME: kang-blogging-sql

