name: Dockerized

on:
  push:
    branches:
      - master

jobs:
  dockerize:
    name: Dockerized
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh blogging

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dockerized
        run: |
          echo 'Building docker image $IMAGE_REPOSITORY:$IMAGE_TAG'
          chmod +x ./scripts/dockerize.sh
          ./scripts/dockerize.sh $IMAGE_TAG $IMAGE_REPOSITORY $TYPE $SERVICE true
        env:
          IMAGE_TAG: m-${{ github.sha }}
          IMAGE_REPOSITORY: truongquangkhang/kang-blogging
          TYPE: app
          SERVICE: blogging

      - name: Docker push
        run: |
          docker push $IMAGE_REPOSITORY:$IMAGE_TAG
        env:
          IMAGE_TAG: m-${{ github.sha }}
          IMAGE_REPOSITORY: truongquangkhang/kang-blogging