name: Trigger auto deployment for kang-blogging

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/kang-blogging-AutoDeployTrigger-56158902-37b6-4e91-a5d2-96d356c1a6d1.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KANGBLOGGING_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.KANGBLOGGING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KANGBLOGGING_REGISTRY_PASSWORD }}
          containerAppName: kang-blogging
          resourceGroup: kang
          imageToBuild: balankhang@gmail.com/kang-blogging:${{ github.sha }}
          
            

     

