name: Trigger auto deployment for kang-blogging-sql

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/kang-blogging-sql-AutoDeployTrigger-aa8f53df-720c-4a56-807e-9a8d5175d6d5.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KANGBLOGGINGSQL_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.KANGBLOGGINGSQL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KANGBLOGGINGSQL_REGISTRY_PASSWORD }}
          containerAppName: kang-blogging-sql
          resourceGroup: kang
          imageToBuild: balankhang1967@gmail.com/truongquangkhang/kang-blogging-sql:${{ github.sha }}
          
            

     

